### ISSUE TITLE
Convert WTV-MetaRenamer.pdf to Wiki Home Page

### ISSUE THREAD

**Issue by coop333** [pcolmer/WTV-MetaRenamer#9]
You had indicated that it would be nice to convert your pdf user guide into another format for GitHub. I have forked your project and created a wiki page based on your pdf. Please review the wiki page that I created and if you like them, please merge them into your project.

https://github.com/coop333/WTV-MetaRenamer/wiki

Thanks, 
Jorel Cooper

**Comment by pcolmer** [comment]
Thank you so much, Jorel, for taking the time to do that.

I noted the comment about the images. I've got the Word document on a different system so I'll try and remember to dig that out at the weekend.

**Comment by pcolmer** [comment]
I've added the Word document to the repository.
